@echo off 
:: ATTENTION: This is GENERATED BY PREMAKE! 
:: ATTENTION: If you edit this, beware that all changes will be lost if premake is executed (again)! 

@echo Executing: %~f0 

set ANDROID_TOOL_BOX_RELATIVE_DIR=../../../AndroidToolBox
set ANDROID_CORE_PACKAGE_RELATIVE_DIR=../../../AndroidFramework
set TYPE_OF_BUILD=%1
set SOLUTION_NAME=jsoncpp
set NATIVE_COMPILER=Gcc4.8
set NATIVE_API_LEVEL=14
set JOBS=4 
rem set setup=%~dp0%ANDROID_CORE_PACKAGE_RELATIVE_DIR%/tools/native/native_setup.bat
rem if not exist %setup% (
    set setup=%~dp0%ANDROID_TOOL_BOX_RELATIVE_DIR%/native_setup.bat
rem )
if not exist %setup% (
    @echo ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR 
    @echo ERROR: Cannot find file: %setup% 
    @echo FIX: In Externals folder must exists AndroidToolBox folder!
    @echo INFO: CheckOut the AndroidToolBox from https://svn02/vc/tools/AndroidToolbox !
    @echo ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR-ERROR 
    exit /B 1 
)

@echo Setup/Check Tools ... 
call %setup% 
if ERRORLEVEL 1 exit /b 1 

python apk/worker.py %1 %2 %3 %4 %5 %6 %7 %8 %9  
